name = "fqs-aero"
version = "0.1.0"
license = "MIT"
author = "Will Dickson"
maintainer = "wbd@caltech.edu"
copyright = "Copyright 2021, Will Dickson"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
